#!/usr/bin/env python3
import hashlib, os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding

def derive_key(str):
    return hashlib.sha256(str.encode('utf-8')).digest()

def decrypt_policy(policy, key):
    iv = policy[:16]
    if len(iv) != 16:
        raise IOError("Failed to read IV from input file")

    cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
    decryptor = cipher.decryptor()
    policy_decrypted = decryptor.update(policy[16:]) + decryptor.finalize()

    try:
        unpadder = padding.PKCS7(128).unpadder()
        return unpadder.update(policy_decrypted) + unpadder.finalize()
    except ValueError:
        print("E: Decryption failed!")
        print("   Make sure you provided the correct policy name. \n")
        exit(1)

def encrypt_policy(policy, key):
    iv = os.urandom(16)

    padder = padding.PKCS7(128).padder()
    policy_padded = padder.update(policy) + padder.finalize()

    cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
    encryptor = cipher.encryptor()
    return iv + encryptor.update(policy_padded) + encryptor.finalize()

def main(policy_file, policy_name, out, mode):
    secret_key = derive_key(policy_name)

    with open(policy_file, 'rb') as f:
        policy = f.read()
    
    if mode == "decrypt":
        output = decrypt_policy(policy, secret_key)
    else:
        output = encrypt_policy(policy, secret_key)

    with open(out, 'wb') as f:
        f.write(output)

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='A tool to decrypt/encrypt SIOP policies for OneUI 8 and later.')
    parser.add_argument('policy_file', help='input file path')
    parser.add_argument('policy_name', help='SIOP policy name (Refer to SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME)')
    parser.add_argument('-o', '--out', help='output file path (default: <policy_name>.xml / siop_model)')

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-d', '--decrypt', action='store_true', help='decrypt the policy (default)')
    group.add_argument('-e', '--encrypt', action='store_true', help='encrypt the policy')
    args = parser.parse_args()

    if not os.path.isfile(args.policy_file):
        print(f"E: No such file: '{args.policy_file}'!")
        exit(1)

    if args.decrypt:
        mode = "decrypt"
        out = args.out if args.out else f"{args.policy_name}.xml"
    else:
        mode = "encrypt"
        out = args.out if args.out else "siop_model"

    main(args.policy_file, args.policy_name, out, mode)
