#!/usr/bin/env python3
import hashlib, os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from pathlib import Path

def derive_key(policy_name):
    return hashlib.sha256(policy_name.encode('utf-8')).digest()

def decrypt_policy(policy, key):
    if len(policy) < 16:
        raise ValueError("Failed to read IV from policy file")

    iv = policy[:16]
    ciphertext = policy[16:]

    cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
    decryptor = cipher.decryptor()
    policy_decrypted = decryptor.update(ciphertext) + decryptor.finalize()

    unpadder = padding.PKCS7(128).unpadder()
    return unpadder.update(policy_decrypted) + unpadder.finalize()

def encrypt_policy(policy, key):
    iv = os.urandom(16)

    padder = padding.PKCS7(128).padder()
    policy_padded = padder.update(policy) + padder.finalize()

    cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
    encryptor = cipher.encryptor()
    return iv + encryptor.update(policy_padded) + encryptor.finalize()

def main(policy_file, policy_name, out, operation):
    key = derive_key(policy_name)
    policy = policy_file.read_bytes()

    output = operation(policy, key)
    out.write_bytes(output)

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='A tool to decrypt and encrypt Samsung SIOP policies.')
    parser.add_argument('policy_file', type=Path, help='input file path')
    parser.add_argument('policy_name', help='SIOP policy name (Refer to SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME)')
    parser.add_argument('-o', '--out', type=Path, help='output file path (default: <policy_name>.xml / siop_model)')

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-d', '--decrypt', action='store_true', help='decrypt the policy')
    group.add_argument('-e', '--encrypt', action='store_true', help='encrypt the policy')
    args = parser.parse_args()

    if args.decrypt:
        out = args.out if args.out else Path(f"{args.policy_name}.xml")
        operation = decrypt_policy
    else:
        out = args.out if args.out else Path("siop_model")
        operation = encrypt_policy

    main(args.policy_file, args.policy_name, out, operation)
